"""Added action column to trades table

Revision ID: c64f06dd5fab
Revises: 34a4e28c6f73
Create Date: 2026-04-22 00:53:15.850357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64f06dd5fab'
down_revision = '34a4e28c6f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('action')

    # ### end Alembic commands ###
